default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", 'localhost') %>
  username: <%= ENV.fetch("DATABASE_USER", 'jesher') %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", '') %>

development:
  <<: *default
  database: mini_score_development

test:
  <<: *default
  database: mini_score_test

production:
  <<: *default
  database: mini_score_production
